call mvn install:install-file -Dfile=javax.jms.jar -DgroupId=javax.jms -DartifactId=javax.jms -Dversion=1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=ojdbc6.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=11.2.0.3 -Dpackaging=jar
call mvn install:install-file -Dfile=json-simple-1.1.1.jar -DgroupId=json-simple-1.1.1 -DartifactId=json-simple-1.1.1 -Dversion=1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=alfresco-repository-3.3.jar -DgroupId=org.alfresco -DartifactId=alfresco-repository -Dversion=3.3 -Dpackaging=jar
call mvn install:install-file -Dfile=alfresco-web-client-3.3.jar -DgroupId=org.alfresco -DartifactId=alfresco-web-client -Dversion=3.3 -Dpackaging=jar
call mvn install:install-file -Dfile=alfresco-web-service-client-3.3.jar -DgroupId=org.alfresco -DartifactId=alfresco-web-service-client -Dversion=3.3 -Dpackaging=jar
call mvn install:install-file -Dfile=axis-1.4.jar -DgroupId=org.axis -DartifactId=axis -Dversion=1.4 -Dpackaging=jar
call mvn install:install-file -Dfile=axis-wsdl4j-1.2.jar -DgroupId=org.axis -DartifactId=axis-wsdl4j -Dversion=1.2 -Dpackaging=jar
call mvn install:install-file -Dfile=SymJavaAPI.jar -DgroupId=com.symantec.scanengine.api -DartifactId=SymJavaAPI -Dversion=1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=java-json.jar -DgroupId=org.json -DartifactId=json-org -Dversion=1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=./dfc.jar -DgroupId=com.documentum -DartifactId=fc -Dversion=1.0 -Dpackaging=jar 
call mvn install:install-file -Dfile=./activation-1.1.jar -DgroupId=javax.activation -DartifactId=activation -Dversion=1.1 -Dpackaging=jar  
call mvn install:install-file -Dfile=./axiom-api-1.2.13.jar -DgroupId=org.apache.ws.commons.axiom -DartifactId=axiom.api -Dversion=1.2.13 -Dpackaging=jar 
call mvn install:install-file -Dfile=./axiom-impl-1.2.13.jar -DgroupId=org.apache.ws.commons.axiom -DartifactId=axiom.impl -Dversion=1.2.13 -Dpackaging=jar 
call mvn install:install-file -Dfile=./axis2-adb-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-adb -Dversion=1.6.2 -Dpackaging=jar 
call mvn install:install-file -Dfile=./axis2-kernel-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-kernel -Dversion=1.6.2 -Dpackaging=jar 
call mvn install:install-file -Dfile=./axis2-transport-http-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-transport-http -Dversion=1.6.2 -Dpackaging=jar 
call mvn install:install-file -Dfile=./axis2-transport-local-1.6.2.jar -DgroupId=org.apache.axis2 -DartifactId=axis2-transport-local -Dversion=1.6.2 -Dpackaging=jar 
call mvn install:install-file -Dfile=./axis-1.4.jar -DgroupId=org.apache.axis -DartifactId=axis -Dversion=1.4 -Dpackaging=jar 
call mvn install:install-file -Dfile=./axis-wsdl4j-1.2.jar -DgroupId=axis -DartifactId=axis-wsdl4j -Dversion=1.2 -Dpackaging=jar 
call mvn install:install-file -Dfile=./commons-codec-1.3.jar -DgroupId=commons-codec -DartifactId=commons-codec -Dversion=1.3 -Dpackaging=jar 
call mvn install:install-file -Dfile=./commons-httpclient-3.1.jar -DgroupId=ommons-httpclient -DartifactId=ommons-httpclient -Dversion=3.1 -Dpackaging=jar 
call mvn install:install-file -Dfile=./geronimo-stax-api_1.0_spec-1.0.1.jar -DgroupId=org.apache.geronimo.specs -DartifactId=geronimo-stax-api_1.0_spec -Dversion=1.0.1 -Dpackaging=jar 
call mvn install:install-file -Dfile=./httpcore-4.0.jar -DgroupId=org.apache.httpcomponents -DartifactId=httpcore -Dversion=4.0 -Dpackaging=jar 
call mvn install:install-file -Dfile=./jaxb-api-2.1.jar -DgroupId=javax.xml.bind -DartifactId=jaxb-api -Dversion=2.1 -Dpackaging=jar 
call mvn install:install-file -Dfile=./jaxb-impl-2.1.7.jar -DgroupId=com.sun.xml.bind -DartifactId=jaxb-impl -Dversion=2.1.7 -Dpackaging=jar 
call mvn install:install-file -Dfile=./mail-1.4.jar -DgroupId=javax.mail -DartifactId=mail -Dversion=1.4 -Dpackaging=jar 
call mvn install:install-file -Dfile=./neethi-3.0.2.jar -DgroupId=org.apache.neethi -DartifactId=neethi -Dversion=3.0.2 -Dpackaging=jar 
call mvn install:install-file -Dfile=./XmlSchema-1.4.7.jar -DgroupId=org.apache.ws.commons.schema -DartifactId=XmlSchema -Dversion=1.4.7 -Dpackaging=jar 
call mvn install:install-file -Dfile=./batik-dom-1.6-1.jar -DgroupId=batik -DartifactId=batik-dom -Dversion=1.6-1 -Dpackaging=jar
call mvn install:install-file -Dfile=./batik-css-1.6-1.jar -DgroupId=batik -DartifactId=batik-css -Dversion=1.6-1 -Dpackaging=jar